Add controllers
Toolll1/java-shareit pull request #2
Opened 2023-05-05 12:21 UTC by Toolll1

2023-05-06 11:20 UTC, TomattmanYandex requested changes
Привет, хорошая работа. сделано даже больше чем надо было, коменты по исправлениям как всегда в коде

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> + * id — уникальный идентификатор бронирования;
комент хорош, но в текущем формате лучше бы подошел каждому отдельному полю
+ многие из подписей даже не нужны ведь и так понятно что id это id start и end время старта и окончания и т.д.

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public BookingDto bookingToDto(Booking booking) {
возможно было бы удобнее назвать методы как objectToDto и dtoToObject зачем каждый раз задумываться о том какой объект ты трансформируешь, это будет понятно по используемому сервису

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepositoryImpl.java
> +        return null;
можно нарваться на ошибку когда будешь это имплементить но забудешь исправить метод
в таких случаях часто вметсо тела метода оставляют создание ошибки NotImplemented

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    public String request;
почему переменная String если будет либо Request либо его id

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    public Integer owner;
если переменная integer то скорее всего там будет хранится id  следоавтельно ее лучше назвать ownerId

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    public Integer owner;
или хранить в ней переменную типа User

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        for (Item item : itemsList) {
преобразование в DTO лучше делать на уровне сервиса и оттуда возвращать уже список DTO

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemMapper.itemToDto(itemService.findById(itemId));
аналогично

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (userService.findById(userId) == null) {
это логика сервиса

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = itemMapper.dtoToItem(dto, userId);
это тоже ллучше в сервисе

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (userService.findById(userId) == null) {
аналогично

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (itemService.findById(itemId).getOwner().equals(userId)) {
аналогично

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        for (Item item : itemsList) {
аналогично

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public List<Item> findAllByOwnerId(Integer userId) {
преобразования из дто и обратно лучше делать на урвоне сервиса
т.е.
сервис получает DTO
сервис его преобразует в объект
сервис использует его (наприме вызывает метод репозитория с этим объектам)
сервис преобразует ответ в дто и возвращает его

Этот комент писать больше не буду

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public Item change(Item item) {
что значит change

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +    Map<Integer, User> users = new HashMap<>();
модификатор доступа

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    private final UserRepository userRepository;
те же коменты что и в фильм сервисе

2023-05-06 11:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    Map<Integer, Item> items = new HashMap<>();
модификатор доступа

2023-05-06 15:57 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    public String request;
В тз было написано, что в этом поле будет ссылка. Я и подумал, что она стринговая будет)

2023-05-06 15:58 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/booking/BookingRepositoryImpl.java
> +        return null;
Я пока реализовал то, что в тз - item и user, этот класс пока оставил, как шаблон для будущих заданий

2023-05-06 15:58 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public BookingDto bookingToDto(Booking booking) {
Ок

2023-05-06 15:59 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> + * id — уникальный идентификатор бронирования;
Увидел такие комментарии у чувака, с кодом которого работали на прошлом ТЗ, мне понравилось) но, нет так нет))

2023-05-06 16:00 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    public Integer owner;
Тоже так думал, но решил оставить имена, как в тз

2023-05-06 16:00 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        for (Item item : itemsList) {
Ок

2023-05-06 16:02 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public Item change(Item item) {
Переводчик сказал, что так правильнее писать "изменение") поменяю на update

2023-05-11 07:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> + * id — уникальный идентификатор бронирования;
это формат JavaDoc и если хочешь посмотреть хорошие примеры коментариев, то можно просто взять любой стандартный класс в библиотеке и глянуть его исходники. Но вообще это коментарий был из разаряда - можно лучше, поэтому если тебе так удобно можно оставить,

2023-05-11 07:29 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public BookingDto bookingToDto(Booking booking) {
у меня тут был на днях таск просто по рефакторингу и изменению имен переменной и класса, и вот за счет таких универсальных имен проблем с изменением имен чуть меньше, потому что встроенными интсрументами легко поменять имя переменной или названия классов, а вот когда это часть имени метода, то сложнее

2023-05-11 07:31 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepositoryImpl.java
> +        return null;
да я понял, это просто способ как поддерживать код легче, ошибку заметить гораздо легче чем правильно сработавший метод, но с неверными значениями

2023-05-11 07:45 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    public String request;
слылка на урвоне базы это внешний ключа чаще всего

2023-05-11 07:54 UTC, TomattmanYandex approved these changes
В основном комментарии раньше были из серии можно лучше. Теперь код  лучше)))
Принято, но не забудь глянуть комментарии которые были ответом на твои комментарии.

2023-05-11 07:54 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        for (Item item : itemsList) {
в таких случаях очень удобно использовать стримы
return // на выходе получим необходимый лист, так что переменную можно не создавать, а сразу возвращать
itemList.stream() // преобразуем лист в стрим
.map(itemMapper::objectToDto) // преобразовываем каждый элемент используя указанный метод аналог .map(item -> itemMapper.objectToDto(item))
.collect.Collectros.toList(); //преобразуем в лист обратно

2023-05-11 07:54 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        for (Item item : itemsList) {
а еще если использовать библиотеки для маппинга то они позволяют определить мапинг для одного обьекта, и по нему делают метод маппинга сразу списка (под капотом он выглядит примерно так же) но все автоматом сгенерено

2023-05-15 06:52 UTC, merged