ТЗ-14 итерация 1 (рубрика "эксперименты")
Toolll1/java-shareit pull request #4
Opened 2023-05-22 08:34 UTC by Toolll1

2023-05-22 13:50 UTC, TomattmanYandex requested changes
Привет, превосходная работа, есть пара несущественных моментов которые стоит гялнуть

2023-05-22 13:50 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllByOwnerIdOrderByStartDesc(Integer userId);
а нужен ли тут запрос, спринг сам должен такой же запрос сформировать для получения данных
по имени метода

2023-05-22 13:50 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (oldBooking.getEnd() == null ||
как много условий, почему бы их не вынести в отдельный метод с понятным именем который в себе будет содержать return и все что в if 
а тут if(название этого метода)

2023-05-22 13:50 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +package ru.practicum.shareit.item;
так как комменты это подструктура в айтемах то лучше вынести в отдельный подпакет в этом пакете
и перенести туда все что их касается

2023-05-22 13:50 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public CommentDto createComment(CommentDto dto, Integer userId, int itemId) {
возможно лучше было бы создать отдельный сервис для комментариев, и в него вынести все методы касающиеся их?

2023-05-22 13:50 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        User newUser = userRepository.save(userMapper.dtoToObject(user));
проверочку бы, на то что юзера с такой почтой нету в базе

2023-05-22 14:55 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllByOwnerIdOrderByStartDesc(Integer userId);
в прошлый раз не получалось)) а теперь работает!

2023-05-22 15:01 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (oldBooking.getEnd() == null ||
+

2023-05-22 15:03 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +package ru.practicum.shareit.item;
+

2023-05-22 15:10 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public CommentDto createComment(CommentDto dto, Integer userId, int itemId) {
+

2023-05-22 15:15 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        User newUser = userRepository.save(userMapper.dtoToObject(user));
+

2023-05-23 18:10 UTC, TomattmanYandex approved these changes
Принято

2023-05-24 19:45 UTC, merged