ТЗ-15 - итерация 1
Toolll1/java-shareit pull request #5
Opened 2023-05-31 15:14 UTC by Toolll1

2023-06-05 15:57 UTC, TomattmanYandex requested changes
ПО основному коду вопросов мало, а вот по тестам вопросов множество
1) нету тестов по многим требованиям
2) на item и request некоторых типов тестов вообще нету
3) непонятно где есть тесты с моками, точнее для чего они там используются

отдельный момент по организации самих тестов
лучше сделать так чтобы на уровне тестовых классов не было никаких переменных кроме переменных с сервисами 
(контроллерами, репозиториями) которые используются . про это я расписал в одном из коментов

Комментарии только в тестах букинга, но проблемы в остальных такие же

2023-06-05 15:57 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                               @RequestParam(value = "from", defaultValue = "0", required = false) Integer from,
когда добавляешьdefaultValue , required = false добавляется автоматически, можно не делать жто вручную

2023-06-05 15:57 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                PageRequest.of(from / size, size)));
создание PageRequest можно вынести в отдельный метод, так как есть логика небольшая, и используется она часто

2023-06-05 15:57 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +    public void create_returnsTheCorrectBookingDto_underNormalConditions() {
контроллеры обычно тестируют через springMvc 
да и по заданию так надо
Реализовать тесты для REST-эндпоинтов вашего приложения с использованием MockMVC. Вам нужно покрыть тестами все существующие эндпоинты. При этом для слоя сервисов используйте моки.

2023-06-05 15:57 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingMapperTests.java
> +    @MockBean
если это тест маппера, то зачем тут нужен репозиторий, ведь маппер от него никак не зависит

2023-06-05 15:57 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingMapperTests.java
> +    UserService userService;
да и от сервиса маппер никак не зависит

2023-06-05 15:57 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTests.java
> +public class BookingRepositoryTests {
Задание 
Реализовать тесты для слоя репозиториев вашего приложения с использованием аннотации @DataJpaTest. Есть смысл написать тесты для тех репозиториев, которые содержат кастомные запросы. 

@DataJpaTest не использовано

2023-06-05 15:57 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTests.java
> +public class BookingRepositoryTests {
да и там дальше в задании написано что имеет смысл протестировать
(зачем тестировать методы спринга, их уже и до нас хорошо протестировали)

2023-06-05 15:57 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingMapperTests.java
> +public class BookingMapperTests {
Реализовать тесты для работы с JSON для DTO в вашем приложении с помощью аннотации @JsonTest.
аннотации даже нету

2023-06-05 15:57 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTests.java
> +    private final ItemController itemController;
если мы тетсируем сервис, то контроллер нам в любом случае не нужен, 
уровень сервиса не должен ничего знать об уровнях выше его

2023-06-05 15:57 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTests.java
> +        creatingObjects();
архитектура теста плоха
1) какой метод мы тестируем? (это понятно)
2) но где мы его используем?
3) что за переменную мы проверяем в блоке assert?
Чтобы сделать хороший тест стоит придерживаться следующих пунктов
1) given when then
можно разбить тело метода на 3 части (часто так коментариями и делают)
//given
код для подготовки данных (например создание обьектов в базе или настройка моков)
//when
вызов тестируемого метода
//then
проверки

2) не стоит хранить в переменной в памяти класса какие то данные для тестов, 
Если хочешь сохранить что то в базу и оставить для проверки, или делай это в самом методе в области given
или если делаешь это через вызов какого то метода, то пускай переменная для сравнения будет в возвращаемом значении

2023-06-05 17:43 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                PageRequest.of(from / size, size)));
странно, но ок

2023-06-05 17:53 UTC, Toolll1 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                               @RequestParam(value = "from", defaultValue = "0", required = false) Integer from,
+

2023-06-07 10:28 UTC, Toolll1 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +    public void create_returnsTheCorrectBookingDto_underNormalConditions() {
+

2023-06-08 10:21 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                PageRequest.of(from / size, size)));
простейший аргумент почему так стоит сделать, сейчас у тебя в параметрах приходит два числа, с  которого начать и сколько, и вдруг меняются требования, и в паарметрах начнает приходить номер страницы и с какого начаать, при предыдущей реализации прийдется лазать по всему коду и искать где ты создавал эти страницы, а с новой реализации, меняешь только в Новом методе и везде работает

2023-06-08 10:23 UTC, TomattmanYandex approved these changes
Принято
хотя мне все еще не очень нравится что на уровне класса в тестах есть какие то переменные
как я уже писал обычно если тебе надо переменная для сравнения то лучше написать метод, который создаст запись в базе, и сразу вернет нужную переменную

2023-06-14 13:44 UTC, merged