Add docker
Toolll1/java-shareit pull request #6
Opened 2023-06-15 06:58 UTC by Toolll1

2023-06-15 13:25 UTC, TomattmanYandex requested changes
Немного но надо переделать

2023-06-15 13:25 UTC, TomattmanYandex commented on docker-compose.yml
> +      - db
гейтвей не зависит от базы никак

2023-06-15 13:25 UTC, TomattmanYandex commented on server/src/main/java/ru/practicum/shareit/ShareItServer.java
> +		System.setProperty("server.port", "9090");
так поступают крайне редко, лучше задать пропертю в application.properties

2023-06-15 13:25 UTC, TomattmanYandex commented on server/src/main/java/ru/practicum/shareit/booking/BookingDto.java
тут остались аннотации валидации

2023-06-15 13:25 UTC, TomattmanYandex commented on pom.xml
> +		<dependency>
Все эти зависимости будут у обоих проектов, но основной части не нужна эта зависимость и валидации, а гейтвею не нужны например библиотеки базы данных

2023-06-15 14:43 UTC, Toolll1 commented on docker-compose.yml
> +      - db
+

2023-06-15 14:45 UTC, Toolll1 commented on server/src/main/java/ru/practicum/shareit/booking/BookingDto.java
+

2023-06-15 15:48 UTC, Toolll1 commented on pom.xml
> +		<dependency>
+

2023-06-15 15:53 UTC, Toolll1 commented on server/src/main/java/ru/practicum/shareit/ShareItServer.java
> +		System.setProperty("server.port", "9090");
+

2023-06-16 11:03 UTC, TomattmanYandex approved these changes
Принято

2023-06-26 13:03 UTC, merged